//
//  GetRefillPoints.swift
//  WaterRefill
//
//  Created by Jithin on 21/01/20.
//  Copyright © 2020 FabCoders. All rights reserved.
//

import UIKit
import Alamofire
import SwiftyJSON

class GetRefillPoints: NetworkRequest<RefillPoint> {

    let GET_REFILL_POINTS_SERVICE = "get_refill_points"
    
    init(_ params: [String : String]) {
           super.init()
           setURL()
           httpMethod = HTTPMethod.post
           addParams(params)
       }
       
       func loadRefillPoints(completion: @escaping ([RefillPoint]) -> Void) {
           load(withCompletion: completion)
       }
       
       override func parseForArray(_ data: Data) -> [RefillPoint] {
        
        let test = Data(getTestData().utf8)
        let json = JSON(test)
        return RefillPointsParser.parse(test)
        
       }
    
       func setURL(){
         URL = getBaseUrl() + GET_REFILL_POINTS_SERVICE
       }
    
    
    func getTestData() -> String{
        return """
        {
            "status": true,
            "code": "200",
            "data": [{
                "refill_id": "38",
                "user_id": "10",
                "place_name": "MOG - Museum Of Goa",
                "contact_no": "77220 89666",
                "address_1": "79, Pilerne Industrial Estate, Pilerne,",
                "address_2": "Pilerne, Goa 403511, India",
                "country": "India",
                "state": "Goa",
                "city": "Pilerne",
                "zip_code": "403511",
                "source_of_drinking": "",
                "last_serviced_date": "17-11-2017",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "",
                "latitude": "15.525516",
                "longitude": "73.795263",
                "opens_at": "09:00 am",
                "closes_at": "06:00 pm",
                "thumbnail": ".//uploads//38//thumbnail2.png",
                "created_on": "2017-10-24 11:39:50",
                "refill_type": "1",
                "refillOrSeller": "2",
                "isApproved": "1",
                "rating": "3.0"
            }, {
                "refill_id": "110",
                "user_id": "53",
                "place_name": "Villa Blanche",
                "contact_no": "9763730029",
                "address_1": "Badem Church Road",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Assagao",
                "zip_code": "403507",
                "source_of_drinking": "tap",
                "last_serviced_date": "1-10-2017",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "restaurant and cafe",
                "latitude": "15.599428078639063",
                "longitude": "73.77538941800594",
                "opens_at": "09:00 am",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//110//thumbnail1.png",
                "created_on": "2017-11-27 10:07:57",
                "refill_type": "1",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": "3.3"
            }, {
                "refill_id": "111",
                "user_id": "53",
                "place_name": "Goa Airport Departure",
                "contact_no": "9763730029",
                "address_1": "Dabolim",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Vasco da Gama",
                "zip_code": "403801",
                "source_of_drinking": "Water Fountain",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "airport",
                "latitude": "15.384875667951443",
                "longitude": "73.83764248341322",
                "opens_at": "12:00 am",
                "closes_at": "11:59 pm",
                "thumbnail": ".//uploads//111//thumbnail.png",
                "created_on": "2017-11-28 06:10:16",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "120",
                "user_id": "49",
                "place_name": "Dunes Restaurant",
                "contact_no": "+918322247219",
                "address_1": "Junos Vaddo",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Mandrem",
                "zip_code": "403527",
                "source_of_drinking": "Tap",
                "last_serviced_date": "1-11-2017",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "restaurant, beach shack",
                "latitude": "15.665973031623096",
                "longitude": "73.71224585920572",
                "opens_at": "08:00 am",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//120//thumbnail.png",
                "created_on": "2017-12-11 09:43:21",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "123",
                "user_id": "48",
                "place_name": "Gokarna Mahabaleshwar Temple",
                "contact_no": "0000000000",
                "address_1": "Gokarna",
                "address_2": "",
                "country": "India",
                "state": "Karnataka",
                "city": "Gokarna",
                "zip_code": "581326",
                "source_of_drinking": "",
                "last_serviced_date": "5-2-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Temple",
                "latitude": "14.543630273207384",
                "longitude": "74.31646138429642",
                "opens_at": "06:00 am",
                "closes_at": "10:00 am",
                "thumbnail": ".//uploads//123//thumbnail.png",
                "created_on": "2017-12-23 06:06:25",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": "0.0"
            }, {
                "refill_id": "125",
                "user_id": "48",
                "place_name": "Murdheshwar Temple",
                "contact_no": "9999999999",
                "address_1": "Murdheshwar",
                "address_2": "Karnataka",
                "country": "India",
                "state": "Karnataka",
                "city": "Murdeshwar",
                "zip_code": "581350",
                "source_of_drinking": "",
                "last_serviced_date": "20-10-2017",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Temple",
                "latitude": "14.094458610312346",
                "longitude": "74.48742672801018",
                "opens_at": "06:00 am",
                "closes_at": "10:00 am",
                "thumbnail": ".//uploads//125//thumbnail.png",
                "created_on": "2017-12-24 02:14:22",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "131",
                "user_id": "49",
                "place_name": "Ruta&#39; Roadhouse",
                "contact_no": "+918380025757",
                "address_1": "Mapusa Anjuna Road",
                "address_2": "Before Happy Bar junction",
                "country": "India",
                "state": "Goa",
                "city": "Assagao",
                "zip_code": "403507",
                "source_of_drinking": "Tap",
                "last_serviced_date": "1-11-2017",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Cafe",
                "latitude": "15.591100608831862",
                "longitude": "73.77076596021652",
                "opens_at": "08:30 am",
                "closes_at": "06:30 pm",
                "thumbnail": ".//uploads//131//thumbnail.png",
                "created_on": "2018-01-02 06:57:13",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "132",
                "user_id": "49",
                "place_name": "Lil Red Door",
                "contact_no": "7350002042",
                "address_1": "204//1 Bergina Park, On NH17",
                "address_2": "Porvorim",
                "country": "India",
                "state": "Goa",
                "city": "Porvorim",
                "zip_code": "403501",
                "source_of_drinking": "Water Filter",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Salon",
                "latitude": "15.537319317961575",
                "longitude": "73.82303014397621",
                "opens_at": "10:00 am",
                "closes_at": "07:30 pm",
                "thumbnail": ".//uploads//132//thumbnail.png",
                "created_on": "2018-01-03 13:29:07",
                "refill_type": "1",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": "5.0"
            }, {
                "refill_id": "139",
                "user_id": "49",
                "place_name": "Basho Cafe",
                "contact_no": "7507500720",
                "address_1": "Arambol beach",
                "address_2": "Nr Drum circle",
                "country": "India",
                "state": "Goa",
                "city": "Arambol",
                "zip_code": "403524",
                "source_of_drinking": "20 ltr container",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "1",
                "images": "",
                "more_about_yourself": "cafe, huts",
                "latitude": "15.68462060308953",
                "longitude": "73.70416201651096",
                "opens_at": "08:00 pm",
                "closes_at": "09:00 pm",
                "thumbnail": ".//uploads//139//thumbnail3.png",
                "created_on": "2018-03-07 12:17:21",
                "refill_type": "0",
                "refillOrSeller": "1",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "141",
                "user_id": "90",
                "place_name": "Planet Hollywood Beach Resort Goa",
                "contact_no": "9769668785",
                "address_1": "Acsona Waddo,",
                "address_2": "Uttorda",
                "country": "India",
                "state": "Goa",
                "city": "Utorda",
                "zip_code": "403713",
                "source_of_drinking": "Water filter",
                "last_serviced_date": "1-3-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Hotel open 24*7",
                "latitude": "15.316171572055596",
                "longitude": "73.90182808041574",
                "opens_at": "12:00 am",
                "closes_at": "11:59 pm",
                "thumbnail": ".//uploads//141//thumbnail.png",
                "created_on": "2018-03-07 13:35:17",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": "25.0"
            }, {
                "refill_id": "145",
                "user_id": "49",
                "place_name": "Carry Your Bottle Office",
                "contact_no": "9763730029",
                "address_1": "294 Sebastian waddo",
                "address_2": "Opp Villa Blanche Bistro",
                "country": "India",
                "state": "Goa",
                "city": "Assagao",
                "zip_code": "403507",
                "source_of_drinking": "20 ltr filter water containers",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "office",
                "latitude": "15.59957727054231",
                "longitude": "73.77523485571145",
                "opens_at": "10:00 am",
                "closes_at": "06:00 pm",
                "thumbnail": ".//uploads//145//thumbnail.png",
                "created_on": "2018-10-25 06:08:46",
                "refill_type": "2",
                "refillOrSeller": "2",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "146",
                "user_id": "313",
                "place_name": "Pappi Chulo Hostel",
                "contact_no": "8007607197",
                "address_1": "Pappi Chulo hostel, near Nine Bar",
                "address_2": "Ozran Beach road, Vagator",
                "country": "India",
                "state": "Goa",
                "city": "Vagator",
                "zip_code": "403509",
                "source_of_drinking": "Manual filter",
                "last_serviced_date": "29-10-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Hostel and bar",
                "latitude": "15.59698997047929",
                "longitude": "73.73638339340687",
                "opens_at": "10:00 am",
                "closes_at": "03:00 am",
                "thumbnail": ".//uploads//146//thumbnail.png",
                "created_on": "2018-10-29 14:47:53",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "147",
                "user_id": "324",
                "place_name": "Sunset Meadows",
                "contact_no": "7057811942",
                "address_1": "1069 Gaowaddi Waddo",
                "address_2": "Anjuna Bardez Goa",
                "country": "India",
                "state": "Goa",
                "city": "Anjuna",
                "zip_code": "403509",
                "source_of_drinking": "Aqua guard",
                "last_serviced_date": "28-10-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Accommodation, Cafe and Fitness Centre",
                "latitude": "15.589162317312633",
                "longitude": "73.75956103205681",
                "opens_at": "09:00 am",
                "closes_at": "12:36 pm",
                "thumbnail": ".//uploads//147//thumbnail.png",
                "created_on": "2018-10-31 07:08:54",
                "refill_type": "1",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "148",
                "user_id": "313",
                "place_name": "Twice in Nature",
                "contact_no": "9999279687",
                "address_1": "Twice In Nature",
                "address_2": "Arambol",
                "country": "India",
                "state": "Goa",
                "city": "Arambol",
                "zip_code": "403524",
                "source_of_drinking": "Bisleri bottle",
                "last_serviced_date": "30-10-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "restaurant and live music venue",
                "latitude": "15.693485244472884",
                "longitude": "73.7042847275734",
                "opens_at": "06:00 pm",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//148//thumbnail.png",
                "created_on": "2018-10-31 09:21:11",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "149",
                "user_id": "313",
                "place_name": "Vaayu Village",
                "contact_no": "8551970222",
                "address_1": "Opposite holy cross chapel north ashwem beach",
                "address_2": "Bardez Goa",
                "country": "India",
                "state": "Goa",
                "city": "Mandrem",
                "zip_code": "403527",
                "source_of_drinking": "big Bisleri bottle",
                "last_serviced_date": "31-10-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "cafe, accommodation and adventure centre",
                "latitude": "15.654817634234583",
                "longitude": "73.71623162180185",
                "opens_at": "09:00 am",
                "closes_at": "10:00 pm",
                "thumbnail": ".//uploads//149//thumbnail.png",
                "created_on": "2018-10-31 10:48:33",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "150",
                "user_id": "313",
                "place_name": "Little World",
                "contact_no": "00919887956810",
                "address_1": "Little World Main Street",
                "address_2": "Palolem Goa",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "Bisleri can 20L",
                "last_serviced_date": "30-3-2018",
                "ready": "0",
                "free": "1",
                "images": "",
                "more_about_yourself": "Restaurant, cafe & bakery",
                "latitude": "15.011972462281188",
                "longitude": "74.02389742434025",
                "opens_at": "08:30 am",
                "closes_at": "10:00 pm",
                "thumbnail": ".//uploads//150//thumbnail.png",
                "created_on": "2018-11-03 10:47:13",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "153",
                "user_id": "313",
                "place_name": "Summer by the Hostelcrowd",
                "contact_no": "08322643406",
                "address_1": "Summer by the hostelcrowd, 99//1",
                "address_2": "Ourem road, Palolem Canacona",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "uv + uf purification",
                "last_serviced_date": "1-9-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "hostel and cafe",
                "latitude": "15.010046290571594",
                "longitude": "74.02933493256569",
                "opens_at": "12:00 am",
                "closes_at": "12:00 pm",
                "thumbnail": ".//uploads//153//thumbnail.png",
                "created_on": "2018-11-04 12:02:21",
                "refill_type": "0",
                "refillOrSeller": "2",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "154",
                "user_id": "324",
                "place_name": "Rainbow Lining Hostel",
                "contact_no": "7030579049",
                "address_1": "Rainbow lining hostel 75 Ourem rd Palolem",
                "address_2": "Behind Cafe Maria",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "Aqua guard filter",
                "last_serviced_date": "30-8-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Hostel",
                "latitude": "15.007955590934733",
                "longitude": "74.02885314077139",
                "opens_at": "09:00 am",
                "closes_at": "09:00 pm",
                "thumbnail": ".//uploads//154//thumbnail.png",
                "created_on": "2018-11-05 08:20:41",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "155",
                "user_id": "313",
                "place_name": "Aloha Surf India",
                "contact_no": "8605476576",
                "address_1": "Aloha Surf India, H. No. 511, Valtambadam",
                "address_2": "Agonda, Canacona",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "Bisleri 20L can",
                "last_serviced_date": "10-11-2018",
                "ready": "0",
                "free": "1",
                "images": "",
                "more_about_yourself": "surf school and shop",
                "latitude": "15.036125206534395",
                "longitude": "73.99074465036392",
                "opens_at": "08:00 am",
                "closes_at": "07:00 pm",
                "thumbnail": ".//uploads//155//thumbnail.png",
                "created_on": "2018-11-15 04:35:44",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "156",
                "user_id": "324",
                "place_name": "The Tribe",
                "contact_no": "096075 40290",
                "address_1": "House no 440//k Palolem Agonda rd",
                "address_2": "Gurukal Canacona 403702",
                "country": "India",
                "state": "Goa",
                "city": "Agonda",
                "zip_code": "403702",
                "source_of_drinking": "Packaged drinking water refill",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Jungle Cafe and guest house",
                "latitude": "15.039495583844506",
                "longitude": "74.01634834706783",
                "opens_at": "09:00 am",
                "closes_at": "06:00 pm",
                "thumbnail": ".//uploads//156//thumbnail.png",
                "created_on": "2018-11-17 09:10:30",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "160",
                "user_id": "313",
                "place_name": "Other-wise",
                "contact_no": "9921581466",
                "address_1": "House no. 375 Khalcha Wada, nr. Narayan Temple",
                "address_2": "Arambol",
                "country": "India",
                "state": "Goa",
                "city": "Arambol",
                "zip_code": "403524",
                "source_of_drinking": "RO filter and Bisleri 20L",
                "last_serviced_date": "5-1-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "restaurant and boutique",
                "latitude": "15.689397221728246",
                "longitude": "73.70503507554531",
                "opens_at": "08:00 am",
                "closes_at": "10:00 pm",
                "thumbnail": ".//uploads//160//thumbnail.png",
                "created_on": "2019-01-09 08:42:58",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "161",
                "user_id": "313",
                "place_name": "Scuba Evolution India",
                "contact_no": "9819900790",
                "address_1": "H.No.840, Villa Sorronto, D&#39;mello Vaddo",
                "address_2": "nr. Starco Junction Goa",
                "country": "India",
                "state": "Goa",
                "city": "Anjuna",
                "zip_code": "403509",
                "source_of_drinking": "RO filter",
                "last_serviced_date": "15-10-2018",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "scuba dive center",
                "latitude": "15.584490255550755",
                "longitude": "73.74174881726503",
                "opens_at": "07:00 am",
                "closes_at": "06:00 pm",
                "thumbnail": ".//uploads//161//thumbnail.png",
                "created_on": "2019-01-09 11:56:40",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "166",
                "user_id": "353",
                "place_name": "Cherwel VALLEY SERVICES",
                "contact_no": "0000000000",
                "address_1": "Junction 10 M40",
                "address_2": "",
                "country": "United Kingdom",
                "state": "England",
                "city": "",
                "zip_code": "OX27 7RD",
                "source_of_drinking": "Costa coffee",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "services",
                "latitude": "51.95007946775451",
                "longitude": "-1.1991331726312637",
                "opens_at": "12:00 am",
                "closes_at": "12:00 am",
                "thumbnail": ".//uploads//166//thumbnail.png",
                "created_on": "2019-01-23 17:01:16",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "168",
                "user_id": "361",
                "place_name": "Sweet earth Goa",
                "contact_no": "9130012014",
                "address_1": "Villa Goesa road",
                "address_2": "Next to Relish restaurant",
                "country": "India",
                "state": "Goa",
                "city": "Calangute",
                "zip_code": "403516",
                "source_of_drinking": "Bisleri 20L bottle",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Sweet earth Goa is a unique shop in Calangute, Goa carrying a mix of earth friendly products, souvenirs and gifts that spark joy. The copper bottles by Carry your bottle were one of the first products we stocked. And we are happy to provide a water refill point to support the cause.",
                "latitude": "15.552545130882407",
                "longitude": "73.75695291906595",
                "opens_at": "05:00 pm",
                "closes_at": "09:00 pm",
                "thumbnail": ".//uploads//168//thumbnail.png",
                "created_on": "2019-02-25 13:52:16",
                "refill_type": "0",
                "refillOrSeller": "2",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "169",
                "user_id": "377",
                "place_name": "Bangkhuntian Animal Hospital",
                "contact_no": "+660889824429",
                "address_1": "84//56 PhraramII road, Soi 65",
                "address_2": "Alley behind the Bangkok bank",
                "country": "Thailand",
                "state": "Krung Thep Maha Nakhon",
                "city": "Bangkok",
                "zip_code": "10150",
                "source_of_drinking": "water ATM",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "1",
                "images": "",
                "more_about_yourself": "Apartment",
                "latitude": "13.65171940629214",
                "longitude": "100.42475368827581",
                "opens_at": "06:00 pm",
                "closes_at": "08:00 pm",
                "thumbnail": ".//uploads//169//thumbnail.png",
                "created_on": "2019-04-30 07:42:39",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "171",
                "user_id": "382",
                "place_name": "Baba Au Rhum",
                "contact_no": "9822866366",
                "address_1": "House no 1054",
                "address_2": "Sim Vaddo",
                "country": "India",
                "state": "Goa",
                "city": "",
                "zip_code": "403509",
                "source_of_drinking": "RO water filter",
                "last_serviced_date": "1-5-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "",
                "latitude": "15.576418612410404",
                "longitude": "73.75577744096518",
                "opens_at": "09:00 am",
                "closes_at": "10:30 pm",
                "thumbnail": ".//uploads//171//thumbnail.png",
                "created_on": "2019-05-20 17:28:24",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "172",
                "user_id": "389",
                "place_name": "The Art Lounge",
                "contact_no": "07843151366",
                "address_1": "Scenery Hill House",
                "address_2": "Branthwaite",
                "country": "United Kingdom",
                "state": "England",
                "city": "Branthwaite",
                "zip_code": "",
                "source_of_drinking": "tap",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "B and B",
                "latitude": "54.611543668993704",
                "longitude": "-3.4542872384190564",
                "opens_at": "09:30 am",
                "closes_at": "09:30 pm",
                "thumbnail": ".//uploads//172//thumbnail.png",
                "created_on": "2019-06-11 16:39:07",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "173",
                "user_id": "51",
                "place_name": "Palm Forest Palolem",
                "contact_no": "00918007727269",
                "address_1": "Behind St Cruz Chapel",
                "address_2": "North End Palolem Beach",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "20L Mineral Water Bottles",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Boutique Hotel & Yoga Shala",
                "latitude": "15.01348314129164",
                "longitude": "74.018899127841",
                "opens_at": "07:00 am",
                "closes_at": "10:00 pm",
                "thumbnail": ".//uploads//173//thumbnail.png",
                "created_on": "2019-07-04 08:23:24",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "176",
                "user_id": "400",
                "place_name": "Pharmacie De L&#39;homme De fer",
                "contact_no": "+33 3 88 23 73 43",
                "address_1": "2 Place de l&#39;Homme de Fer, 67000 Strasbourg, France",
                "address_2": "",
                "country": "France",
                "state": "Grand Est",
                "city": "Strasbourg",
                "zip_code": "67000",
                "source_of_drinking": "Water Fountain",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "chemist",
                "latitude": "48.584167684651284",
                "longitude": "7.744945585727692",
                "opens_at": "09:00 am",
                "closes_at": "07:15 pm",
                "thumbnail": ".//uploads//176//thumbnail.png",
                "created_on": "2019-07-17 16:40:52",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "177",
                "user_id": "49",
                "place_name": "Camp Hornbill",
                "contact_no": "9456143370",
                "address_1": "Village Kyari, P.O. Ramnagar,",
                "address_2": "Dist. Nainital, Uttarakhand, Kiari Bandobast.",
                "country": "India",
                "state": "Uttarakhand",
                "city": "Hatkar",
                "zip_code": "244715",
                "source_of_drinking": "Govt. Supply and river water",
                "last_serviced_date": "1-6-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Camp Hornbill is a community-led enterprise, set up in 2010 by residents of the village Kyari. It lies within the Pawalgarh Conservation Reserve, a part of the larger Corbett Tiger Reserve in Uttarakhand India.\nIt was established with a vision to promote and encourage ecotourism in the village of Kyari. At Camp Hornbill our aim is to seed an alternative form of nature travel that is responsible and contributes to nature conservation and community development. The Camp is visited by all 3 species of Hornbills found in this landscape, and hence the name.",
                "latitude": "30.103758833604537",
                "longitude": "79.06952854245901",
                "opens_at": "09:02 pm",
                "closes_at": "07:03 pm",
                "thumbnail": ".//uploads//177//thumbnail.png",
                "created_on": "2019-08-27 09:33:46",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "178",
                "user_id": "417",
                "place_name": "Nireas Healthy Haven",
                "contact_no": "7057578854",
                "address_1": "Palolem Down Street",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "government",
                "last_serviced_date": "12-9-2019",
                "ready": "0",
                "free": "1",
                "images": "",
                "more_about_yourself": "We care for the environment and our aim is to leave a light footprint. We not only care for our natural environment but also for our health. That&#39;s why in our restaurant you find a lot of eco friendly alternatives and homemade food.",
                "latitude": "15.0119400789057",
                "longitude": "74.02447309345007",
                "opens_at": "08:30 am",
                "closes_at": "10:30 pm",
                "thumbnail": ".//uploads//178//thumbnail.png",
                "created_on": "2019-09-13 01:18:11",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": "5.0"
            }, {
                "refill_id": "179",
                "user_id": "49",
                "place_name": "Sascha",
                "contact_no": "06765645997",
                "address_1": "Gabesstra\\u00dfe 36",
                "address_2": "",
                "country": "Austria",
                "state": "Ober\\u00f6sterreich",
                "city": "Linz",
                "zip_code": "4030",
                "source_of_drinking": "",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "",
                "latitude": "48.24532972126999",
                "longitude": "14.305504448711872",
                "opens_at": "05:25 pm",
                "closes_at": "02:40 pm",
                "thumbnail": ".//uploads//179//thumbnail.png",
                "created_on": "2019-10-13 15:24:48",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "186",
                "user_id": "51",
                "place_name": "Millys Place",
                "contact_no": "9923759503",
                "address_1": "Dhumaney agonda palolem road canacona Goa",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "filter water",
                "last_serviced_date": "29-11-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "restaurant",
                "latitude": "15.032382726903316",
                "longitude": "74.02150455862284",
                "opens_at": "10:00 am",
                "closes_at": "03:30 pm",
                "thumbnail": ".//uploads//186//thumbnail.png",
                "created_on": "2019-11-29 06:16:27",
                "refill_type": "2",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "187",
                "user_id": "51",
                "place_name": "Jaali Boutique And Cafe",
                "contact_no": "08007712248",
                "address_1": "Patnem-Palolem Road, Patnem, Canacona, Goa",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "filtered water",
                "last_serviced_date": "21-10-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "Jaali Boutique and Cafe is a restaurant and boutique in Patnem Canacona. We are in our fifth season and are proud to say we have NEVER sold plastic water bottles in our restaurant. We have always offered filtered water and a fill your bottle service\\u00a0.",
                "latitude": "14.99974155997453",
                "longitude": "74.03403449803591",
                "opens_at": "09:00 am",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//187//thumbnail.png",
                "created_on": "2019-12-04 10:52:49",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "188",
                "user_id": "316",
                "place_name": "Jaali Cafe",
                "contact_no": "8007712248",
                "address_1": "Patnem - Palolem Road",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Canacona",
                "zip_code": "403702",
                "source_of_drinking": "Wlwctric water filter",
                "last_serviced_date": "31-10-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "A middle eastern inspired tapas restaurant in a lovely garden setting.",
                "latitude": "14.99978042224235",
                "longitude": "74.03400097042322",
                "opens_at": "09:00 am",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//188//thumbnail.png",
                "created_on": "2019-12-10 11:05:15",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "195",
                "user_id": "51",
                "place_name": "Alitia Food",
                "contact_no": "7262076857",
                "address_1": "Chapora near ganesh juce center",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Chapora",
                "zip_code": "403509",
                "source_of_drinking": "filtered",
                "last_serviced_date": "Choose date",
                "ready": "0",
                "free": "3",
                "images": "",
                "more_about_yourself": "we serve the best coffe,waffles,crepes and sandwiches made with love .Do come visit us",
                "latitude": "15.603726182875988",
                "longitude": "73.74176155775785",
                "opens_at": "05:00 pm",
                "closes_at": "03:00 am",
                "thumbnail": ".//uploads//195//thumbnail.png",
                "created_on": "2020-01-07 13:13:34",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "196",
                "user_id": "51",
                "place_name": "Morjim Olive Ridley Nesting Site",
                "contact_no": "09819572544",
                "address_1": "Morjim Beach ,403512",
                "address_2": "",
                "country": "India",
                "state": "Goa",
                "city": "Morjim",
                "zip_code": "403519",
                "source_of_drinking": "Bisleri 20 ltrs",
                "last_serviced_date": "9-1-2020",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "",
                "latitude": "15.61680562221739",
                "longitude": "73.73330421745777",
                "opens_at": "03:00 pm",
                "closes_at": "06:30 pm",
                "thumbnail": ".//uploads//196//thumbnail.png",
                "created_on": "2020-01-10 12:47:58",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }, {
                "refill_id": "197",
                "user_id": "51",
                "place_name": "Bean Me Up",
                "contact_no": "9021980602",
                "address_1": "Deaul waddo , ozran beach road vagator bardez goa",
                "address_2": "Near vagator petrol station",
                "country": "India",
                "state": "Goa",
                "city": "Vagator",
                "zip_code": "403509",
                "source_of_drinking": "filtered water",
                "last_serviced_date": "26-12-2019",
                "ready": "0",
                "free": "0",
                "images": "",
                "more_about_yourself": "",
                "latitude": "15.59612193239747",
                "longitude": "73.74821361154318",
                "opens_at": "08:00 am",
                "closes_at": "11:00 pm",
                "thumbnail": ".//uploads//197//thumbnail.png",
                "created_on": "2020-01-14 07:22:54",
                "refill_type": "0",
                "refillOrSeller": "0",
                "isApproved": "1",
                "rating": null
            }]
        }
      """
    }
}
